### ISSUE TITLE
Use odvc instead of vendorizing the equations

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/x-stairs#4]
[`odvc`](https://github.com/ioos/odvc) already have the most important non-dimensional vertical coordinates. We need to add the atmospheric ones and just import it here.

**Comment by kshedstrom** [comment]
Will you be trying all this out in Ocean Hack Week?

What is the best way to support the MOM6 files? Through a PR to odvc? What's the best way to get you a small MOM6 file? email?

**Comment by ocefpaf** [comment]
> Will you be trying all this out in Ocean Hack Week?

I'm planning too. Let's track it in this issue.

> What is the best way to support the MOM6 files? Through a PR to odvc?

I think so. We need to add the formula to `odvc`.

> What's the best way to get you a small MOM6 file? email?

E-mail works (You'll find mine in our hackpad). I'll setup a git-lfs for us to host test cases.

**Comment by ocefpaf** [comment]
This issue is solved in #6. We need a new one to track the MOM6 equation though.
